<a href="https://colab.research.google.com/github/t-zakharenko/ML-course-May-2025/blob/main/HW_2_1_%D0%9C%D0%B0%D1%82%D1%80%D0%B8%D1%86%D1%96_%D1%96_%D0%B2%D0%B5%D0%BA%D1%82%D0%BE%D1%80%D0%B8_(%D0%B2%D1%81%D1%82%D1%83%D0%BF_%D0%B4%D0%BE_%D0%BB%D1%96%D0%BD_%D0%B0%D0%BB%D0%B3%D0%B5%D0%B1%D1%80%D0%B8)_TZ.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [4]:
import numpy as np
import random

In [9]:
'''
Завдання 1_1: Створення матриць та векторів

Створіть numpy вектор vector розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1.
Можна скористатись двома альтернативними варіантами:

Генерація випадкових чисел з модулем random.uniform.
Створення вектора з допомогою метода numpy np.random.rand
'''

# Варіант 1. Генерація випадкових чисел з модулем random.uniform.
vector = np.array([random.uniform(0, 1) for _ in range(10)])
print("\n\nВектор, створений з допомогою метода random.uniform:")
print(vector)

# Варіант 2. Створення вектора з допомогою метода numpy np.random.rand
vector = np.random.rand(10)
print("\n\nВектор, створений за допомогою генераціх випадкових чисел з np.random.rand:")
print(vector)



Вектор, створений з допомогою метода random.uniform:
[0.24566801 0.27537694 0.21978705 0.99292166 0.27631176 0.33168398
 0.93284093 0.22465706 0.42052281 0.94270101]


Вектор, створений за допомогою генераціх випадкових чисел з np.random.rand:
[0.92260904 0.4653188  0.51631752 0.14992371 0.13323794 0.44637196
 0.64058114 0.32686863 0.05844541 0.54700657]


In [23]:
'''
Завдання 1_2: Створення матриці matrix типу numpy.array розмірності 3х3 зі значеннями:
[[11 14 17]
 [20 23 26]
 [29 32 35]]

'''

matrix = np.array([
    [11, 14, 17],
    [20, 23, 26],
    [29, 32, 35]
])

print("\nЗавдання 1_2: Матриця 3x3:\n")
print(matrix)



Завдання 1_2: Матриця 3x3:

[[11 14 17]
 [20 23 26]
 [29 32 35]]



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного `vector` без циклів.


In [33]:
'''
Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
'''

# 1. Додайте до кожного значення вектора vector число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
vector_add_10 = np.round(vector + 10, 2)
print("Початковий вектор: \n", vector)
print("Новий вектор: \n", vector_add_10, "\n\n")

# 2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
matrix_x_2 = matrix * 2
print("Матриця, помножена на 2:")
print(matrix_x_2)

# 3. Створіть новий вектор, який містить квадрат кожного vector без циклів.

Початковий вектор: 
 [0.92260904 0.4653188  0.51631752 0.14992371 0.13323794 0.44637196
 0.64058114 0.32686863 0.05844541 0.54700657]
Новий вектор: 
 [10.92 10.47 10.52 10.15 10.13 10.45 10.64 10.33 10.06 10.55] 


Матриця, помножена на 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отрмаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [34]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0,1], [1,0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [43]:
# Множення матриць
result_matrix = np.dot(B, A)
print("result_matrix (A * B):")
print(result_matrix)

result_matrix (A * B):
[[0.7281 0.5202]
 [0.2034 0.2846]]


In [47]:
# Множення матриці на вектор
print("Множення result_matrix на вектор C:")
print(np.dot(result_matrix, C))

Множення result_matrix на вектор C:
[[0.5202]
 [0.2846]]


In [49]:
# Множення матриць
print("Множення result_matrix на матрицю D:")
print(np.dot(result_matrix, D))

Множення result_matrix на матрицю D:
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [56]:
'''
Завдання 4: Транспонування матриць

'''
# Транспонуйте result_matrix.
transposed_matrix = result_matrix.T
print("Оригінальна матриця result_matrix:")
print(result_matrix)
print("\nТранспонована матриця:")
print(transposed_matrix)

Оригінальна матриця result_matrix:
[[0.7281 0.5202]
 [0.2034 0.2846]]

Транспонована матриця:
[[0.7281 0.2034]
 [0.5202 0.2846]]


Форма матриці залишилася, але значення помінялися місцями.

In [58]:
# Зробіть транспонування вектора vector і виведіть форму нової структури.
transposed_vector = vector.T
print("Оригінальний вектор:")
print(vector)
print("\nТранспонований вектор:")
print(transposed_vector)

Оригінальний вектор:
[0.92260904 0.4653188  0.51631752 0.14992371 0.13323794 0.44637196
 0.64058114 0.32686863 0.05844541 0.54700657]

Транспонований вектор:
[0.92260904 0.4653188  0.51631752 0.14992371 0.13323794 0.44637196
 0.64058114 0.32686863 0.05844541 0.54700657]


Змін не відбулося

In [59]:
# Використайте операцію numpy.expand_dims над вектором vector з аргументом axis=1. Запишіть отриманий результат в змінну column_vector і виведіть на екран. Порівняйте з vector.
column_vector = np.expand_dims(vector, axis=1)
print("Оригінальний вектор:")
print(vector)
print("\nОновлений вектор:")
print(column_vector)
print("column_vector (розмірність):", column_vector.shape)

Оригінальний вектор:
[0.92260904 0.4653188  0.51631752 0.14992371 0.13323794 0.44637196
 0.64058114 0.32686863 0.05844541 0.54700657]

Оновлений вектор:
[[0.92260904]
 [0.4653188 ]
 [0.51631752]
 [0.14992371]
 [0.13323794]
 [0.44637196]
 [0.64058114]
 [0.32686863]
 [0.05844541]
 [0.54700657]]
column_vector (розмірність): (10, 1)


Отримали вектор-колонку.

In [62]:
# Зробіть транспонування column_vector, виведіть результат на екран разом з розмірностями отриманої структури.
transposed_column_vector = column_vector.T
print("Вектор column_vector:")
print(column_vector)
print("Розмірність column_vector:", column_vector.shape)
print("\nТранспонований column_vector:")
print(transposed_column_vector)
print("Розмірність transposed_column_vector:", transposed_column_vector.shape)

Вектор column_vector:
[[0.92260904]
 [0.4653188 ]
 [0.51631752]
 [0.14992371]
 [0.13323794]
 [0.44637196]
 [0.64058114]
 [0.32686863]
 [0.05844541]
 [0.54700657]]
Розмірність column_vector: (10, 1)

Транспонований column_vector:
[[0.92260904 0.4653188  0.51631752 0.14992371 0.13323794 0.44637196
  0.64058114 0.32686863 0.05844541 0.54700657]]
Розмірність transposed_column_vector: (1, 10)


Знову повернули горизонтальний вектор. Змінилась форма.